#!/bin/bash

BRANCH=`git rev-parse --abbrev-ref HEAD`
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
pushebranch=$(git rev-parse --symbolic --abbrev-ref $1)




echo "Current Branch is $current_branch"
echo "Branch is $BRANCH"
echo "pushed branch $pushebranch"
echo "$remote_ref"

while read local_ref local_sha remote_ref remote_sha 
do 
    echo $local_ref
    echo $local_sha 
    echo $remote_ref
    echo $remote_sha

done
	 


[[ $(cat $1) =~ [A-Z]+-[0-9]+.* ]] || {
    echo >&2 "ERROR: Commit message requires JIRA key. Example: \"ABC-123: Test Commit\""
    exit 1
}

